<?php

namespace Admin\Bundle\Entity;

/**
 * diplomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class diplomeRepository extends \Doctrine\ORM\EntityRepository
{
}
