<?php

namespace Admin\Bundle\Entity;

/**
 * EmploiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploiRepository extends \Doctrine\ORM\EntityRepository
{
}
