<?php

namespace Admin\Bundle\Entity;

/**
 * filiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class filiereRepository extends \Doctrine\ORM\EntityRepository
{
}
