<?php

namespace Admin\Bundle\Entity;

/**
 * resultatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class resultatRepository extends \Doctrine\ORM\EntityRepository
{
}
