Admin\Bundle\Entity\Response:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        sendTo:
            type: string
            length: 255
        subject:
            type: string
            length: 255
        message:
            type: text
    lifecycleCallbacks: {  }
