<?php

namespace Proxies\__CG__\Admin\Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Matiere extends \Admin\Bundle\Entity\Matiere implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Admin\\Bundle\\Entity\\Matiere' . "\0" . 'id', '' . "\0" . 'Admin\\Bundle\\Entity\\Matiere' . "\0" . 'nomMatiere', '' . "\0" . 'Admin\\Bundle\\Entity\\Matiere' . "\0" . 'typeMatiere', '' . "\0" . 'Admin\\Bundle\\Entity\\Matiere' . "\0" . 'coefficient', '' . "\0" . 'Admin\\Bundle\\Entity\\Matiere' . "\0" . 'duree', '' . "\0" . 'Admin\\Bundle\\Entity\\Matiere' . "\0" . 'idEnseignant');
        }

        return array('__isInitialized__', '' . "\0" . 'Admin\\Bundle\\Entity\\Matiere' . "\0" . 'id', '' . "\0" . 'Admin\\Bundle\\Entity\\Matiere' . "\0" . 'nomMatiere', '' . "\0" . 'Admin\\Bundle\\Entity\\Matiere' . "\0" . 'typeMatiere', '' . "\0" . 'Admin\\Bundle\\Entity\\Matiere' . "\0" . 'coefficient', '' . "\0" . 'Admin\\Bundle\\Entity\\Matiere' . "\0" . 'duree', '' . "\0" . 'Admin\\Bundle\\Entity\\Matiere' . "\0" . 'idEnseignant');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Matiere $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdEnseignant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEnseignant', array());

        return parent::getIdEnseignant();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEnseignant(\Admin\Bundle\Entity\Enseignant $idEnseignant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEnseignant', array($idEnseignant));

        return parent::setIdEnseignant($idEnseignant);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomMatiere($nomMatiere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomMatiere', array($nomMatiere));

        return parent::setNomMatiere($nomMatiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomMatiere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomMatiere', array());

        return parent::getNomMatiere();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeMatiere($typeMatiere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeMatiere', array($typeMatiere));

        return parent::setTypeMatiere($typeMatiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeMatiere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeMatiere', array());

        return parent::getTypeMatiere();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoefficient($coefficient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoefficient', array($coefficient));

        return parent::setCoefficient($coefficient);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoefficient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoefficient', array());

        return parent::getCoefficient();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuree($duree)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuree', array($duree));

        return parent::setDuree($duree);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuree', array());

        return parent::getDuree();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString1', array());

        return parent::__toString1();
    }

}
