enseignant:
    path:    /
    defaults: { _controller: "AdmiScoBundle:Enseignant:index" }

enseignant_show:
    path:     /{id}/show
    defaults: { _controller: "AdmiScoBundle:Enseignant:show" }

enseignant_new:
    path:     /new
    defaults: { _controller: "AdmiScoBundle:Enseignant:new" }

enseignant_create:
    path:     /create
    defaults: { _controller: "AdmiScoBundle:Enseignant:create" }
    methods:  POST

enseignant_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdmiScoBundle:Enseignant:edit" }

enseignant_update:
    path:     /{id}/update
    defaults: { _controller: "AdmiScoBundle:Enseignant:update" }
    methods:  [POST, PUT]

enseignant_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdmiScoBundle:Enseignant:delete" }
    methods:  [POST, DELETE]
