etudiant:
    path:     /
    defaults: { _controller: "AdmiScoBundle:Etudiant:index" }

etudiant_show:
    path:     /{id}/show
    defaults: { _controller: "AdmiScoBundle:Etudiant:show" }

etudiant_new:
    path:     /new
    defaults: { _controller: "AdmiScoBundle:Etudiant:new" }

etudiant_create:
    path:     /create
    defaults: { _controller: "AdmiScoBundle:Etudiant:create" }
    methods:  POST

etudiant_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdmiScoBundle:Etudiant:edit" }

etudiant_update:
    path:     /{id}/update
    defaults: { _controller: "AdmiScoBundle:Etudiant:update" }
    methods:  [POST, PUT]

etudiant_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdmiScoBundle:Etudiant:delete" }
    methods:  [POST, DELETE]
