semestre:
    path:     /
    defaults: { _controller: "AdmiScoBundle:Semestre:index" }

semestre_show:
    path:     /{id}/show
    defaults: { _controller: "AdmiScoBundle:Semestre:show" }

semestre_new:
    path:     /new
    defaults: { _controller: "AdmiScoBundle:Semestre:new" }

semestre_create:
    path:     /create
    defaults: { _controller: "AdmiScoBundle:Semestre:create" }
    methods:  POST

semestre_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdmiScoBundle:Semestre:edit" }

semestre_update:
    path:     /{id}/update
    defaults: { _controller: "AdmiScoBundle:Semestre:update" }
    methods:  [POST, PUT]

semestre_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdmiScoBundle:Semestre:delete" }
    methods:  [POST, DELETE]
